// <auto-generated />
using System;
using DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTO.Migrations
{
    [DbContext(typeof(FastFoodDBContext))]
    [Migration("20240716032758_NET106")]
    partial class NET106
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.Property<Guid>("AdminCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<bool>("IsOnl")
                        .HasColumnType("bit");

                    b.Property<bool>("Level")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("AdminCode");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerEmail")
                        .IsUnique();

                    b.ToTable("carts");
                });

            modelBuilder.Entity("Models.CartItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<Guid>("Code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("Code");

                    b.ToTable("cartItems");
                });

            modelBuilder.Entity("Models.Combo", b =>
                {
                    b.Property<Guid>("ComboCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComboName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("Varchar(Max)");

                    b.Property<int>("PreviousPrice")
                        .HasColumnType("int");

                    b.HasKey("ComboCode");

                    b.ToTable("combos");
                });

            modelBuilder.Entity("Models.ComboDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ComboCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodCode")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComboCode");

                    b.HasIndex("FoodCode");

                    b.ToTable("comboDetails");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("PassWord")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("UserName")
                        .HasColumnType("Varchar(300)");

                    b.HasKey("Email");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Models.CustomerInformation", b =>
                {
                    b.Property<int>("CInforId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CInforId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("Char(10)");

                    b.HasKey("CInforId");

                    b.HasIndex("CustomerEmail");

                    b.ToTable("customerInformations");
                });

            modelBuilder.Entity("Models.Food", b =>
                {
                    b.Property<Guid>("FoodCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int");

                    b.Property<Guid>("FCategoryCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FoodName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("Varchar(Max)");

                    b.Property<int>("Left")
                        .HasColumnType("int");

                    b.Property<int>("PreviousPrice")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.HasKey("FoodCode");

                    b.HasIndex("AdminCode");

                    b.HasIndex("FCategoryCode");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("Models.FoodCategory", b =>
                {
                    b.Property<Guid>("FCategoryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FCategoryCode");

                    b.ToTable("foodCategories");
                });

            modelBuilder.Entity("Models.Guest", b =>
                {
                    b.Property<int>("GuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuesId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("Char(10)");

                    b.HasKey("GuesId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("guests");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Property<Guid>("OrderCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CInforId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("Nvarchar(Max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("OrderCode");

                    b.HasIndex("CustomerEmail");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Models.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<Guid>("Code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("Code");

                    b.HasIndex("OrderCode");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("Models.Cart", b =>
                {
                    b.HasOne("Models.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("Models.Cart", "CustomerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Models.CartItem", b =>
                {
                    b.HasOne("Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Food", "Food")
                        .WithMany("CartItems")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Models.ComboDetail", b =>
                {
                    b.HasOne("Models.Combo", "Combo")
                        .WithMany("Details")
                        .HasForeignKey("ComboCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Food", "Food")
                        .WithMany("ComboDetail")
                        .HasForeignKey("FoodCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Models.CustomerInformation", b =>
                {
                    b.HasOne("Models.Customer", "Customer")
                        .WithMany("CustomerInformations")
                        .HasForeignKey("CustomerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Models.Food", b =>
                {
                    b.HasOne("Models.Admin", "Admin")
                        .WithMany("foods")
                        .HasForeignKey("AdminCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.FoodCategory", "FoodCategory")
                        .WithMany("foods")
                        .HasForeignKey("FCategoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("FoodCategory");
                });

            modelBuilder.Entity("Models.Guest", b =>
                {
                    b.HasOne("Models.Order", "Order")
                        .WithOne("Guest")
                        .HasForeignKey("Models.Guest", "OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.HasOne("Models.Customer", "Customer")
                        .WithMany("orders")
                        .HasForeignKey("CustomerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Models.OrderItem", b =>
                {
                    b.HasOne("Models.Food", "Food")
                        .WithMany("OrderItems")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Models.Admin", b =>
                {
                    b.Navigation("foods");
                });

            modelBuilder.Entity("Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Models.Combo", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CustomerInformations");

                    b.Navigation("orders");
                });

            modelBuilder.Entity("Models.Food", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ComboDetail");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Models.FoodCategory", b =>
                {
                    b.Navigation("foods");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Navigation("Guest");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
