USE NET106_ASM_FastFood;

CREATE OR ALTER TRIGGER AUTO_SET_SOLD
ON foods
FOR INSERT
AS
	BEGIN
		UPDATE foods
		SET Sold = 0
		WHERE FoodCode = (SELECT FoodCode FROM inserted)
	END
GO

CREATE OR ALTER TRIGGER AUTO_DELETE_RELATED_CUSTOMERS
ON customers
INSTEAD OF DELETE
AS
	BEGIN
		DECLARE @CARTID INT;
		DECLARE @CINFORID INT;
		DECLARE @ORDERCODE UNIQUEIDENTIFIER;
		SET @CARTID = (SELECT CartId FROM carts WHERE CustomerEmail = (SELECT Email FROM deleted));
		SET @CINFORID = (SELECT CInforId FROM customerInformations WHERE CustomerEmail = (SELECT Email FROM deleted));
		SET @ORDERCODE = (SELECT OrderCode FROM orders WHERE CustomerEmail = (SELECT Email FROM deleted));
		DELETE FROM orderItems WHERE OrderCode = @ORDERCODE;
		DELETE FROM orders WHERE OrderCode = @ORDERCODE;
		DELETE FROM carts WHERE CartId = @CARTID;
		DELETE FROM customers WHERE Email = (SELECT Email FROM deleted);
	END
GO

CREATE OR ALTER TRIGGER AUTO_DELETE_RELATED_GUESTS
ON guests
INSTEAD OF DELETE
AS
	BEGIN
		DECLARE @ORDERCODE UNIQUEIDENTIFIER;
		SET @ORDERCODE = (SELECT OrderCode FROM orders WHERE OrderCode = (SELECT OrderCode FROM deleted));
		DELETE FROM orderItems WHERE OrderCode = @ORDERCODE;
		DELETE FROM orders WHERE OrderCode = @ORDERCODE;
		DELETE FROM guests WHERE OrderCode = (SELECT OrderCode FROM deleted);
	END
GO

CREATE OR ALTER TRIGGER AUTO_CREATE_CART
ON customers
AFTER INSERT
AS
	BEGIN
		DECLARE @EMAIL VARCHAR(MAX);
		DECLARE @COUNT INT;
		DECLARE @ID INT;
		SET @COUNT = 0;
		SET @ID = (SELECT COUNT(CartId) FROM carts) + 1; 

		WHILE EXISTS (SELECT * FROM carts WHERE CartId = @ID)
			BEGIN
				SET @COUNT = @COUNT + 1;
				SET @ID = @ID + @COUNT;
			END

		SET @EMAIL = (SELECT Email FROM inserted);
		INSERT INTO carts (CartId, CustomerEmail) values (@ID, @EMAIL);
	END
GO

CREATE OR ALTER TRIGGER DECREASE_QUANTITY_FOOD
ON orderitems
AFTER INSERT
AS
	BEGIN
		DECLARE @FOODCODE UNIQUEIDENTIFIER, @QUANTITY INT;
		DECLARE INSERTCUSOR CURSOR FOR
		SELECT FoodCode, Quantity
		FROM inserted;

		OPEN INSERTCUSOR;

		FETCH NEXT FROM INSERTCUSOR INTO @FOODCODE, @QUANTITY;

		WHILE @@FETCH_STATUS = 0
		BEGIN
			UPDATE foods
			SET Sold = @QUANTITY, [Left] -= @QUANTITY
			WHERE FoodCode = @FOODCODE;

			FETCH NEXT FROM INSERTCUSOR INTO @FOODCODE, @QUANTITY;
		END

		CLOSE INSERTCUSOR;
		DEALLOCATE INSERTCUSOR;
	END	
GO